### ISSUE TITLE
Bug: TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by exp-alchandler** [clineamb/gulp-s3-upload#61]
env: 
- node 8.15.0
- npm 6.4.1
- gulp 3.9.1
- gulp-s3-upload 1.7.2

When trying to upload my project i received the error:
```TypeError: mime.lookup is not a function```

the same script works fine in `gulp-s3-upload 1.7.1`

**Comment by jozecuervo** [comment]
The issue is that `mime` was bumped to 2.x in `gulp-s3-upload` a few days ago and there were breaking changes which were not addressed.

**lookup() renamed to getType()**

**Comment by brainlessboy** [comment]
node v11.0.0
npm 6.4.1
gulp@3.9.1
gulp-s3-upload@1.7.2

same here, reverted to earlier version 1.7.1 and it works ..

**Comment by clineamb** [comment]
yikes, sorry about this folks. going to bump with a downgrade version

**Comment by clineamb** [comment]
I'll publish an upgraded and fixed version later this week. Thanks for sticking with it all~

**Comment by jozecuervo** [comment]
No problem and sorry to bother on such a rough week. I heard about the layoffs after I posted this PR. I hope your colleagues are doing ok.
